// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKdBouToCqhACSPIJoo7qNAuDlK2AviS8',
    appId: '1:52254677844:web:a937cef9532a0180ef06c1',
    messagingSenderId: '52254677844',
    projectId: 'authentication-a2c58',
    authDomain: 'authentication-a2c58.firebaseapp.com',
    storageBucket: 'authentication-a2c58.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1su5Ceeup1VzOW_ZzZR-cItRLWEuZffk',
    appId: '1:52254677844:android:90379dc9d0ef2d7cef06c1',
    messagingSenderId: '52254677844',
    projectId: 'authentication-a2c58',
    storageBucket: 'authentication-a2c58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjZAPSvNXGlxyHYa9PL7EoZ0dR-IQ-Cdk',
    appId: '1:52254677844:ios:f9acb2fc2cc4fae1ef06c1',
    messagingSenderId: '52254677844',
    projectId: 'authentication-a2c58',
    storageBucket: 'authentication-a2c58.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjZAPSvNXGlxyHYa9PL7EoZ0dR-IQ-Cdk',
    appId: '1:52254677844:ios:f9acb2fc2cc4fae1ef06c1',
    messagingSenderId: '52254677844',
    projectId: 'authentication-a2c58',
    storageBucket: 'authentication-a2c58.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKdBouToCqhACSPIJoo7qNAuDlK2AviS8',
    appId: '1:52254677844:web:cf709b769587b712ef06c1',
    messagingSenderId: '52254677844',
    projectId: 'authentication-a2c58',
    authDomain: 'authentication-a2c58.firebaseapp.com',
    storageBucket: 'authentication-a2c58.firebasestorage.app',
  );

}